"""empty message

Revision ID: 0a97b52725cc
Revises: 
Create Date: 2022-08-08 00:58:24.270032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a97b52725cc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("Venue", "venues")
    op.rename_table("Artist", "artists")
    op.create_table(
        "shows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("artists", sa.Column("website", sa.String(), nullable=False))
    op.add_column("artists", sa.Column("seeking_venue", sa.Boolean(), nullable=False))
    op.add_column(
        "artists", sa.Column("seeking_description", sa.String(), nullable=True)
    )
    op.alter_column("artists", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "artists", "genres", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "artists", "city", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "artists", "state", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "artists", "phone", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "artists", "facebook_link", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "artists", "image_link", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.add_column("venues", sa.Column("genres", sa.ARRAY(sa.String()), nullable=False))
    op.add_column("venues", sa.Column("website", sa.String(), nullable=False))
    op.add_column("venues", sa.Column("seeking_talent", sa.Boolean(), nullable=False))
    op.add_column(
        "venues", sa.Column("seeking_description", sa.String(), nullable=True)
    )
    op.alter_column("venues", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "venues", "address", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "venues", "city", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "venues", "state", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "venues", "phone", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "venues", "facebook_link", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "venues", "image_link", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("venues", "Venue")
    op.rename_table("artists", "Artist")
    op.alter_column(
        "Venue", "image_link", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "Venue", "facebook_link", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "Venue", "phone", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "Venue", "state", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "Venue", "city", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "Venue", "address", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column("Venue", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("Venue", "seeking_description")
    op.drop_column("Venue", "seeking_talent")
    op.drop_column("Venue", "website")
    op.drop_column("Venue", "genres")
    op.alter_column(
        "Artist", "image_link", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "Artist", "facebook_link", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "Artist", "phone", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "Artist", "state", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "Artist", "city", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "Artist", "genres", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column("Artist", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("Artist", "seeking_description")
    op.drop_column("Artist", "seeking_venue")
    op.drop_column("Artist", "website")
    op.drop_table("shows")
    # ### end Alembic commands ###
